"""Unit tests for FITS 4.0 CHECKSUM/DATASUM verification.

Reference vectors live in tests/data/*.fits; they were generated by the
independent astropy implementation so that verifying them here proves
interoperability, not just self-consistency.
"""

from __future__ import annotations

import os
import unittest

from fits_cutout import checksum, fits
from tests import fits_build

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")


def load_fixture(name: str) -> bytes:
    with open(os.path.join(DATA_DIR, name), "rb") as handle:
        return handle.read()


def verify_bytes(data: bytes) -> int:
    image = fits.parse(data)
    return checksum.verify(data, image.header_size)


class ValidChecksumTests(unittest.TestCase):
    def test_astropy_int16_fixture(self):
        data = load_fixture("checksum_int16.fits")
        self.assertEqual(verify_bytes(data), 2149056548)

    def test_astropy_int32_fixture(self):
        # The quoted value is right-padded with spaces: '123212  '.
        raw = load_fixture("checksum_int32.fits")
        self.assertIn(b"DATASUM = '123212  '", raw)
        self.assertEqual(verify_bytes(raw), 123212)

    def test_astropy_multiblock_header_fixture(self):
        # Header spans two 2880-byte blocks; header padding is signed too.
        data = load_fixture("checksum_multiblock.fits")
        image = fits.parse(data)
        self.assertEqual(image.header_size, 2 * 2880)
        self.assertEqual(checksum.verify(data, image.header_size), 393210)

    def test_self_signed_files_verify(self):
        for bitpix, pixels in ((16, [1, -2, 3, -4]), (32, [100000, -1])):
            data = fits_build.build_signed_fits(
                bitpix, 2, 2, pixels
            )
            self.assertEqual(verify_bytes(data), verify_bytes(data))
            # And again through the public entry point.
            self.assertIsInstance(verify_bytes(data), int)

    def test_datasum_includes_data_padding(self):
        # 1x1 int16 -> 2 pixel bytes + 2878 zero padding bytes, all signed.
        data = fits_build.build_signed_fits(16, 1, 1, [42])
        datasum = verify_bytes(data)
        # First big-endian word of the data block is 0x002A followed by zeros.
        self.assertEqual(datasum, 42 << 16)


class MissingAndDuplicateCardTests(unittest.TestCase):
    def _signed(self) -> bytes:
        return fits_build.build_signed_fits(16, 2, 1, [1, 2])

    def test_missing_checksum(self):
        data = fits_build.build_fits(16, 2, 1, [1, 2])
        image = fits.parse(data)
        with self.assertRaisesRegex(checksum.ChecksumError, "CHECKSUM card is missing"):
            checksum.verify(data, image.header_size)

    def test_missing_datasum(self):
        # Keep a (zero-valued) CHECKSUM card but drop DATASUM.
        data = fits_build.build_fits(
            16,
            2,
            1,
            [1, 2],
            extra_cards=[fits_build.raw_card("CHECKSUM= '" + "a" * 16 + "'")],
        )
        image = fits.parse(data)
        with self.assertRaisesRegex(checksum.ChecksumError, "DATASUM card is missing"):
            checksum.verify(data, image.header_size)

    def test_duplicate_checksum(self):
        data = fits_build.build_fits(
            16,
            2,
            1,
            [1, 2],
            extra_cards=[
                fits_build.raw_card("CHECKSUM= '" + "a" * 16 + "'"),
                fits_build.raw_card("CHECKSUM= '" + "b" * 16 + "'"),
            ],
        )
        image = fits.parse(data)
        with self.assertRaisesRegex(checksum.ChecksumError, "CHECKSUM card must be unique"):
            checksum.verify(data, image.header_size)

    def test_duplicate_datasum(self):
        data = fits_build.build_fits(
            16,
            2,
            1,
            [1, 2],
            extra_cards=[
                fits_build.raw_card("DATASUM = '123'"),
                fits_build.raw_card("DATASUM = '456'"),
            ],
        )
        image = fits.parse(data)
        with self.assertRaisesRegex(checksum.ChecksumError, "DATASUM card must be unique"):
            checksum.verify(data, image.header_size)


class MalformedCardTests(unittest.TestCase):
    CHECKSUM_OK = "CHECKSUM= '" + "a" * 16 + "'"

    def _assert(self, data: bytes, needle: str):
        image = fits.parse(data)
        with self.assertRaisesRegex(checksum.ChecksumError, needle):
            checksum.verify(data, image.header_size)

    def _build(self, checksum_card: str, datasum_card: str) -> bytes:
        return fits_build.build_fits(
            16,
            2,
            1,
            [1, 2],
            extra_cards=[
                fits_build.raw_card(checksum_card),
                fits_build.raw_card(datasum_card),
            ],
        )

    def test_datasum_without_indicator(self):
        data = fits_build.build_fits(
            16,
            2,
            1,
            [1, 2],
            extra_cards=[
                fits_build.raw_card(self.CHECKSUM_OK),
                fits_build.raw_card("DATASUM   12345    "),
            ],
        )
        self._assert(data, "value card")

    def test_datasum_unquoted(self):
        data = self._build(self.CHECKSUM_OK, "DATASUM = 12345")
        self._assert(data, "quoted string")

    def test_datasum_not_numeric(self):
        data = fits_build.build_fits(
            16,
            2,
            1,
            [1, 2],
            extra_cards=[
                fits_build.raw_card("CHECKSUM= '" + "a" * 16 + "'"),
                fits_build.raw_card("DATASUM = 'abc'"),
            ],
        )
        self._assert(data, "unsigned decimal integer")

    def test_datasum_empty_string(self):
        data = fits_build.build_fits(
            16,
            2,
            1,
            [1, 2],
            extra_cards=[
                fits_build.raw_card("CHECKSUM= '" + "a" * 16 + "'"),
                fits_build.raw_card("DATASUM = ''"),
            ],
        )
        self._assert(data, "unsigned decimal integer")

    def test_datasum_too_large(self):
        data = fits_build.build_fits(
            16,
            2,
            1,
            [1, 2],
            extra_cards=[
                fits_build.raw_card("CHECKSUM= '" + "a" * 16 + "'"),
                fits_build.raw_card("DATASUM = '4294967296'"),
            ],
        )
        self._assert(data, "32-bit range")

    def test_checksum_wrong_length(self):
        data = fits_build.build_fits(
            16,
            2,
            1,
            [1, 2],
            extra_cards=[
                fits_build.raw_card("CHECKSUM= '" + "a" * 15 + "'"),
                fits_build.raw_card("DATASUM = '1'"),
            ],
        )
        self._assert(data, "16 characters")

    def test_checksum_illegal_character(self):
        data = fits_build.build_fits(
            16,
            2,
            1,
            [1, 2],
            extra_cards=[
                fits_build.raw_card("CHECKSUM= '" + "a" * 4 + ":" + "a" * 11 + "'"),
                fits_build.raw_card("DATASUM = '1'"),
            ],
        )
        self._assert(data, "illegal character")

    def test_checksum_unclosed_quote(self):
        data = fits_build.build_fits(
            16,
            2,
            1,
            [1, 2],
            extra_cards=[
                fits_build.raw_card("CHECKSUM= '" + "a" * 16 + " "),
                fits_build.raw_card("DATASUM = '1'"),
            ],
        )
        self._assert(data, "closing apostrophe")

    def test_checksum_trailing_junk(self):
        data = fits_build.build_fits(
            16,
            2,
            1,
            [1, 2],
            extra_cards=[
                fits_build.raw_card("CHECKSUM= '" + "a" * 16 + "'x"),
                fits_build.raw_card("DATASUM = '1'"),
            ],
        )
        self._assert(data, "unexpected characters")


class TamperTests(unittest.TestCase):
    def setUp(self):
        self.data = bytearray(
            fits_build.build_signed_fits(
                16,
                3,
                1,
                [1, 2, 3],
                extra_cards=[fits_build.raw_card("COMMENT integrity probe marker")],
            )
        )

    def tamper(self, offset: int, value: int) -> bytes:
        mutated = bytearray(self.data)
        mutated[offset] = value
        return bytes(mutated)

    def test_original_passes(self):
        self.assertIsInstance(verify_bytes(bytes(self.data)), int)

    def test_pixel_byte_fails(self):
        with self.assertRaises(checksum.ChecksumError):
            verify_bytes(self.tamper(2880 + 1, self.data[2880 + 1] ^ 0xFF))

    def test_data_padding_fails_directly(self):
        # Parse rejects nonzero padding first through the HTTP path; the
        # checksum layer itself must still flag the byte.
        mutated = self.tamper(2880 + 6, 0x01)
        with self.assertRaises(checksum.ChecksumError):
            checksum.verify(mutated, fits.BLOCK_SIZE)

    def test_header_padding_fails_directly(self):
        mutated = self.tamper(2879, ord("X"))
        with self.assertRaises(checksum.ChecksumError):
            checksum.verify(mutated, fits.BLOCK_SIZE)

    def test_comment_card_byte_fails(self):
        # A comment rewrite keeps the file structurally parseable but must
        # invalidate the checksum.
        marker = bytes(self.data).find(b"integrity probe marker")
        self.assertGreater(marker, 0)
        mutated = self.tamper(marker, ord("Z"))
        image = fits.parse(mutated)  # still parses
        with self.assertRaisesRegex(checksum.ChecksumError, "CHECKSUM mismatch"):
            checksum.verify(mutated, image.header_size)

    def test_stored_datasum_rewrite_fails(self):
        offset = bytes(self.data).find(b"DATASUM = '") + len("DATASUM = '")
        mutated = self.tamper(offset, ord("7"))
        image = fits.parse(mutated)
        with self.assertRaises(checksum.ChecksumError):
            checksum.verify(mutated, image.header_size)

    def test_stored_checksum_rewrite_fails(self):
        offset = bytes(self.data).find(b"CHECKSUM= '") + len("CHECKSUM= '")
        mutated = self.tamper(offset, ord("M"))
        image = fits.parse(mutated)
        with self.assertRaisesRegex(checksum.ChecksumError, "CHECKSUM mismatch"):
            checksum.verify(mutated, image.header_size)


class EncodingTests(unittest.TestCase):
    def test_encoded_values_are_legal_ascii(self):
        # Every possible 16-bit-ish input exercises all byte quartets.
        seen = set()
        for value in range(0, 1 << 16):
            text = checksum.encode_checksum(value)
            self.assertEqual(len(text), 16)
            for ch in text:
                code = ord(ch)
                self.assertNotIn(code, range(0x3A, 0x41))
                self.assertNotIn(code, range(0x5B, 0x61))
                self.assertTrue(0x30 <= code <= 0x7A)
            seen.add(text)

    def test_encode_is_deterministic(self):
        self.assertEqual(
            checksum.encode_checksum(0xDEADBEEF),
            checksum.encode_checksum(0xDEADBEEF),
        )

    def test_signed_file_signature_matches_astropy_fixture(self):
        # Same pixels as checksum_int32.fits -> DATASUM must match exactly.
        ours = fits_build.build_signed_fits(32, 2, 2, [5, -250, 0, 123456])
        theirs = load_fixture("checksum_int32.fits")
        self.assertEqual(verify_bytes(ours), verify_bytes(theirs))


if __name__ == "__main__":
    unittest.main()
